[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "resume_api_backend"
version = "2.0.0"
description = "Resume API backend with JWT improvements"
